### ISSUE TITLE
Streamlit UI throws error if no image is uploaded

### ISSUE THREAD

**Issue by davidefiocco** [davidefiocco/streamlit-fastapi-model-serving#7]
If no image is uploaded and segmentation is requested, the UI shows:

![image](https://user-images.githubusercontent.com/4547987/85950935-17789980-b960-11ea-9329-beadbc83ad1f.png)

This case should be handled more cleanly with a clearer message.

**Comment by robmarkcole** [comment]
I get around this by [having a defult image](https://github.com/robmarkcole/text-insights-app/blob/e590c3b791ad8b55735f3b50dd48a48515797e0a/streamlit-ui/ui.py#L35) and caching the result of process

**Comment by davidefiocco** [comment]
In https://github.com/davidefiocco/streamlit-fastapi-model-serving/pull/10 I display some text message in case no image is uploaded.
